---
abstract: 'Base classes wrapping fundamental Perl data types.'
author:
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires:
  Test::Deep: '0'
  Test::Fatal: '0'
  Test::Output: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Perl
requires:
  Class::Method::Modifiers: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Module::Runtime: '0'
  Role::Tiny: '0'
  Scalar::Util: '0'
  parent: '0'
  strictures: '0'
resources:
  bugtracker: https://github.com/tobyink/Data-Perl/issues
  homepage: https://github.com/tobyink/Data-Perl
  repository: https://github.com/tobyink/Data-Perl.git
version: '0.002011'
x_contributors:
  - 'Graham Knop <haarg@haarg.org>'
  - 'Jon Portnoy <avenj@cobaltirc.org>'
  - 'kristof.pap@gmail.com <kristof.pap@gmail.com>'
  - 'Matt Phillips <mattp@cpan.org>'
  - 'Toby Inkster <tobyink@cpan.org>'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
